
package com.example.petstore;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PetPortType", targetNamespace = "urn:com:example:petstore")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PetPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.petstore.PetType
     */
    @WebMethod(action = "getPetById")
    @WebResult(name = "getPetByIdResponse", targetNamespace = "urn:com:example:petstore", partName = "parameters")
    public PetType getPetById(
        @WebParam(name = "getPetByIdRequest", targetNamespace = "urn:com:example:petstore", partName = "parameters")
        GetPetByIdRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.petstore.PetType
     */
    @WebMethod(action = "getPetByName")
    @WebResult(name = "getPetByNameResponse", targetNamespace = "urn:com:example:petstore", partName = "parameters")
    public PetType getPetByName(
        @WebParam(name = "getPetByNameRequest", targetNamespace = "urn:com:example:petstore", partName = "parameters")
        GetPetByNameRequest parameters);

}
