FROM outofcoffee/imposter

MAINTAINER Pete Cornish <outofcoffee@gmail.com>

ENTRYPOINT ["java", "-jar", "/opt/imposter/bin/imposter.jar", "--plugin", "com.gatehill.imposter.plugin.hbase.HBasePluginImpl", "--configDir", "/opt/imposter/config"]
