FROM outofcoffee/imposter

MAINTAINER Pete Cornish <outofcoffee@gmail.com>

CMD ["-Dcom.gatehill.imposter.plugin=com.gatehill.imposter.plugin.rest.RestPluginImpl", "-Dcom.gatehill.imposter.configDir=/opt/imposter/config"]
