FROM outofcoffee/imposter

MAINTAINER Pete Cornish <outofcoffee@gmail.com>

ENTRYPOINT ["java", "-jar", "/opt/imposter/imposter.jar", "--plugin", "com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl", "--configDir", "/opt/imposter/config"]
