name: Integration test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    env:
      AWS_REGION: "eu-west-1"
      TESTCONTAINERS_RYUK_DISABLED: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up build environment
        run: |
          chmod +x ./scripts/*.sh
          # Disable gradle daemon
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Build distributions
        run: ./gradlew dist --stacktrace -xtest

      - name: Integration test
        run: |
          ./scripts/docker-build.sh -p false dev
          ./scripts/integration-tests.sh outofcoffee/imposter:dev
          ./scripts/integration-tests.sh outofcoffee/imposter-all:dev
